# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: alauga_pitomnik
      POSTGRES_USER: pitomnik_user
      POSTGRES_PASSWORD: supersecretpassword
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --worker-class uvicorn.workers.UvicornWorker
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: