# Generated by Django 5.1 on 2025-12-17 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время выгрузки')),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Формат')),
                ('students_count', models.PositiveIntegerField(verbose_name='Количество студентов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог выгрузки',
                'verbose_name_plural': 'Логи выгрузок',
                'ordering': ['-exported_at'],
            },
        ),
    ]
