# Generated by Django 5.1 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportlog',
            name='students_count',
            field=models.PositiveIntegerField(verbose_name='Количество колледжистов'),
        ),
    ]
