# Generated by Django 5.1 on 2026-01-14 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('direction', models.CharField(max_length=200, verbose_name='Направление')),
                ('subdivision', models.CharField(help_text='Где работает/учится', max_length=200, verbose_name='Подразделение')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фото студента')),
                ('level', models.CharField(choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный')], default='black', max_length=10, verbose_name='Уровень доступа')),
                ('status', models.CharField(choices=[('active', 'Активные'), ('fired', 'Уволенные'), ('called_hr', 'Вызваны к HR')], default='active', max_length=20, verbose_name='Статус')),
                ('category', models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (СНГ)'), ('alabuga_mulatki', 'Алабуга Старт (МИР)')], max_length=30, verbose_name='Категория')),
                ('address_actual', models.TextField(verbose_name='Фактический адрес проживания')),
                ('address_registered', models.TextField(verbose_name='Адрес по прописке')),
                ('phone_personal', models.CharField(max_length=20, unique=True, verbose_name='Личный телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram (@username)')),
                ('phone_parent', models.CharField(max_length=20, verbose_name='Телефон родителя/представителя')),
                ('fio_parent', models.CharField(max_length=200, verbose_name='ФИО родителя/представителя')),
                ('medical_info', models.TextField(blank=True, null=True, verbose_name='Медицинские данные')),
                ('last_changed_field', models.CharField(blank=True, help_text='Автоматически заполняется при смене уровня/статуса', max_length=200, null=True, verbose_name='Последнее изменённое поле')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='students/medical_files/', verbose_name='Медицинский файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='students.student')),
            ],
            options={
                'verbose_name': 'Медицинский файл',
                'verbose_name_plural': 'Медицинские файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.CharField(choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный')], max_length=10)),
                ('new_level', models.CharField(choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='students.student')),
            ],
            options={
                'verbose_name': 'История изменения уровня',
                'verbose_name_plural': 'Истории изменений уровней',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
