# Generated by Django 5.1.7 on 2025-12-02 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('direction', models.CharField(max_length=200, verbose_name='Направление')),
                ('subdivision', models.CharField(help_text='Где работает/учится', max_length=200, verbose_name='Подразделение')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('level', models.CharField(choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный')], default='black', max_length=10, verbose_name='Уровень доступа')),
                ('status', models.CharField(choices=[('active', 'Активные'), ('fired', 'Уволенные'), ('called_hr', 'Вызваны к HR')], default='active', max_length=20, verbose_name='Статус')),
                ('category', models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (колледжисты)'), ('alabuga_mulatki', 'Алабуга Старт (мулатки)')], max_length=30, verbose_name='Категория')),
                ('address_actual', models.TextField(verbose_name='Фактический адрес проживания')),
                ('address_registered', models.TextField(verbose_name='Адрес по прописке')),
                ('phone_personal', models.CharField(max_length=20, unique=True, verbose_name='Личный телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram (@username)')),
                ('phone_parent', models.CharField(max_length=20, verbose_name='Телефон родителя/представителя')),
                ('fio_parent', models.CharField(max_length=200, verbose_name='Фио родителя/представителя')),
                ('medical_info', models.TextField(blank=True, null=True, verbose_name='Медицинские данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент (Кот)',
                'verbose_name_plural': 'Студенты (Коты)',
                'ordering': ['-created_at'],
                'permissions': [('can_change_level', 'Может менять уровень доступа'), ('can_view_medical_info', 'Может видеть мед.данные')],
            },
        ),
        migrations.CreateModel(
            name='LevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.CharField(choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный')], max_length=10)),
                ('new_level', models.CharField(choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='students.student')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['level'], name='students_st_level_2a2a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['category'], name='students_st_categor_508d89_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone_personal'], name='students_st_phone_p_58a2d7_idx'),
        ),
    ]
