# Generated by Django 5.1 on 2026-01-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelhistory',
            name='new_level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), (None, 'Без уровня')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='levelhistory',
            name='old_level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), (None, 'Без уровня')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), (None, 'Без уровня')], max_length=10, null=True, verbose_name='Уровень доступа'),
        ),
    ]
