# Generated by Django 5.1.7 on 2025-12-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_changed_field',
            field=models.CharField(blank=True, help_text='Автоматически заполняется при смене уровня/статуса', max_length=200, null=True, verbose_name='Последнее изменённое поле'),
        ),
    ]
