# Generated by Django 5.1 on 2025-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_last_changed_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (колледжисты)'), ('alabuga_mulatki', 'Алабуга Старт (МИР)')], max_length=30, verbose_name='Категория'),
        ),
    ]
