# Generated by Django 5.1 on 2026-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_levelhistory_new_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_called_to_hr',
            field=models.BooleanField(default=False, help_text='Установите True для вызова к HR', verbose_name='Вызван к HR'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активные'), ('fired', 'Уволенные')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
