# Generated by Django 5.1 on 2025-12-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (колледжисты)'), ('alabuga_mulatki', 'Алабуга Старт (мулатки)')], max_length=30, verbose_name='Категория'),
        ),
    ]
