# Generated by Django 5.1 on 2025-12-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_age_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (СНГ)'), ('alabuga_mulatki', 'Алабуга Старт (МИР)')], max_length=30, verbose_name='Категория'),
        ),
    ]
