# Generated by Django 5.1 on 2026-01-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_called_to_hr_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start_rf', 'Алабуга Старт (РФ)'), ('alabuga_start_sng', 'Алабуга Старт (СНГ)'), ('alabuga_mulatki', 'Алабуга Старт (МИР)')], max_length=30, verbose_name='Категория'),
        ),
    ]
