# Generated by Django 5.1 on 2025-12-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_level', 'Может менять уровень доступа'), ('can_view_medical_info', 'Может видеть мед.данные')], 'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фото студента'),
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='students/medical_files/', verbose_name='Медицинский файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='students.student')),
            ],
            options={
                'verbose_name': 'Медицинский файл',
                'verbose_name_plural': 'Медицинские файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
