# Generated by Django 5.1 on 2026-01-22 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к студенту', 'verbose_name_plural': 'Комментарии к студентам'},
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
    ]
