# Generated by Django 5.1 on 2026-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_options_student_photo_medicalfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_level', 'Может менять уровень доступа'), ('can_view_medical_info', 'Может видеть мед.данные')], 'verbose_name': 'Студент (Кот)', 'verbose_name_plural': 'Студенты (Коты)'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (колледжисты)'), ('alabuga_mulatki', 'Алабуга Старт (МИР)')], max_length=30, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='MedicalFile',
        ),
    ]
