# Generated by Django 5.1 on 2026-01-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_comment_options_medicalfile_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.CreateModel(
            name='LevelByMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)])),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('level', models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('fired', 'Уволен')], max_length=10, null=True)),
                ('fired_date', models.DateField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('change_count', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_by_month', to='students.student')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
