# Generated by Django 5.1 on 2026-01-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_options_remove_student_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='students/medical_files/', verbose_name='Медицинский файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Медицинский файл',
                'verbose_name_plural': 'Медицинские файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_level_2a2a2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_status_5e2210_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_categor_508d89_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_phone_p_58a2d7_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фото студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('college', 'Колледжисты'), ('patriot', 'Патриоты'), ('alabuga_start', 'Алабуга Старт (СНГ)'), ('alabuga_mulatki', 'Алабуга Старт (МИР)')], max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fio_parent',
            field=models.CharField(max_length=200, verbose_name='ФИО родителя/представителя'),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='students.student'),
        ),
    ]
