# Generated by Django 5.1 on 2026-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_levelbymonth_month_alter_levelbymonth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelbymonth',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='levelbymonth',
            name='year',
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)]),
        ),
    ]
