# Generated by Django 5.1 on 2026-02-03 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_levelbymonth_month_alter_levelbymonth_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_di',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средний ДИ'),
        ),
        migrations.AddField(
            model_name='student',
            name='average_mbo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средний МБО'),
        ),
        migrations.AddField(
            model_name='student',
            name='average_ws',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средний WS'),
        ),
        migrations.AddField(
            model_name='student',
            name='kvazar_rank',
            field=models.CharField(blank=True, choices=[('sergeant', 'Сержант'), ('private', 'Рядовой'), ('reserve', 'Запас')], max_length=20, null=True, verbose_name='Участие в Квазаре'),
        ),
        migrations.AddField(
            model_name='student',
            name='olympiads_participation',
            field=models.TextField(blank=True, null=True, verbose_name='Участие в олимпиадах'),
        ),
        migrations.AddField(
            model_name='student',
            name='rating_place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в рейтинге'),
        ),
        migrations.CreateModel(
            name='ViolationAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание нарушения/акта')),
                ('file', models.FileField(blank=True, null=True, upload_to='students/violation_acts/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_acts', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Объяснительная/Акт',
                'verbose_name_plural': 'Объяснительные и Акты',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
