# Generated by Django 5.1 on 2026-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_average_di_student_average_mbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Фактический адрес проживания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_registered',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес по прописке'),
        ),
        migrations.AlterField(
            model_name='student',
            name='direction',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fio_parent',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО родителя/представителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_parent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон родителя/представителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_personal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Личный телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subdivision',
            field=models.CharField(blank=True, help_text='Где работает/учится', max_length=200, null=True, verbose_name='Подразделение'),
        ),
    ]
