# Generated by Django 5.1 on 2026-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_direction_alter_student_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelbymonth',
            name='level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('fired', 'Уволен'), ('', 'Без уровня')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='levelhistory',
            name='new_level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('fired', 'Уволен'), ('', 'Без уровня')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='levelhistory',
            name='old_level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('fired', 'Уволен'), ('', 'Без уровня')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('fired', 'Уволен'), ('', 'Без уровня')], max_length=10, null=True, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subdivision',
            field=models.CharField(blank=True, choices=[('hr', 'Управление HR'), ('ssr', 'Служба Стратегического Развития(ССР)'), ('ssp', 'Служба Специальных Проектов(ССП)'), ('kb', 'Конструкторское Бюро(КБ)'), ('srnp', 'Служба Развития Новых Площадок(СРНП)'), ('agd', 'Администрация Генерального Директора(АГД)'), ('stoitr', 'Стройтрест'), ('aldi', 'Алабуга Девелопмент(АЛДИ)'), ('economika', 'Управление экономикой'), ('invest', 'Управление привлечения инвестиций'), ('kapstroy', 'Управление капитального строительства'), ('ekspl', 'Управление эксплуатации и энергетики'), ('arenda', 'Департамент арендного бизнеса'), ('security', 'Служба безопасности и пропускного режима'), ('admin_arenda', 'Служба администрирования арендного жилья'), ('digital', 'Управление цифровой трансформации'), ('edu_admin', 'Служба администрирования образовательного кластера'), ('logist', 'Департамент логистики'), ('urid', 'Юридическая служба'), ('production', 'Производственное подразделение'), ('finance', 'Управление финансами'), ('central_warehouse', 'Центральный склад'), ('residents', 'Управление по взаимодействию с резидентами'), ('projects_group', 'Управление группы проектов'), ('project_kopty', 'Проект "Копты"'), ('kb2', 'Конструкторское бюро №2'), ('deputy_office', 'Аппарат заместителя генерального директора'), ('corp', 'Департамент по корпоративным вопросам'), ('sng', 'Управление по взаимодействию с СНГ'), ('mashinnery', 'Машиннери'), ('alma', 'АлМа'), ('chess', 'Шахматы'), ('drake', 'Дрейк'), ('siemens', 'Зименс'), ('gea', 'ГЭА'), ('project_office', 'Проектный офис'), ('admin_module', 'Административный модуль'), ('acct_tax', 'Управление бухгалтерского и налогового учета')], help_text='Где работает/учится', max_length=200, null=True, verbose_name='Подразделение'),
        ),
    ]
