# Generated by Django 5.1 on 2026-02-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_levelbymonth_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('black', 'Чёрный'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('fired', 'Уволен'), ('', 'Без уровня')], default='', max_length=10, verbose_name='Уровень доступа'),
        ),
    ]
