# Generated by Django 5.1 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к колледжисту', 'verbose_name_plural': 'Комментарии к колледжистам'},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фото колледжиста'),
        ),
    ]
