# Generated by Django 5.1 on 2026-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_fired_date_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelbymonth',
            name='fired_date_precision',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fired_date_precision',
        ),
    ]
