# Generated by Django 5.1 on 2026-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_levelbymonth_fired_date_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('graduate', 'Выпускник')], max_length=10, null=True, verbose_name='Курс'),
        ),
    ]
