# Generated by Django 5.1 on 2026-01-14 07:34

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта')),
                ('telegram', models.CharField(blank=True, help_text='Имя пользователя в Telegram (без @)', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя Telegram должно содержать только латинские буквы, цифры и подчеркивания (5-32 символа)', regex='^[a-zA-Z0-9_]{5,32}$')], verbose_name='Telegram')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('hr', 'HR'), ('med', 'Медслужба'), ('saok', 'САОК'), ('admin', 'Админ')], default='hr', max_length=20, verbose_name='Роль')),
                ('position', models.CharField(blank=True, help_text='Официальная должность в организации', max_length=200, null=True, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация о себе', max_length=1000, null=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, help_text='Рекомендуемый размер: 300x300 пикселей', max_length=500, null=True, upload_to=apps.users.models.user_avatar_upload_path, verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
