# Generated by Django 5.1 on 2026-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('med', 'Медслужба'), ('saok', 'САОК'), ('admin', 'Админ'), ('super_admin', 'Супер админ')], default='hr', help_text='Роль super_admin назначается только автоматически первому суперюзеру.', max_length=20, verbose_name='Роль'),
        ),
    ]
