# Generated by Django 5.1 on 2025-11-28 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('med', 'Медслужба'), ('saok', 'САОК'), ('admin', 'Админ')], default='hr', max_length=20, verbose_name='Роль'),
        ),
    ]
