# Generated by Django 5.1 on 2026-01-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер админ'), ('admin', 'Админ'), ('hr', 'HR'), ('saok', 'САОК'), ('med', 'Медслужба')], default='hr', help_text='Роль super_admin назначается только автоматически первому пользователю.', max_length=20, verbose_name='Роль'),
        ),
    ]
