# Generated by Django 5.1.7 on 2025-12-04 14:40

import apps.users.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 300x300 пикселей', max_length=500, null=True, upload_to=apps.users.models.user_avatar_upload_path, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткая информация о себе', max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Официальная должность в организации', max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='Имя пользователя в Telegram (без @)', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя Telegram должно содержать только латинские буквы, цифры и подчеркивания (5-32 символа)', regex='^[a-zA-Z0-9_]{5,32}$')], verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
    ]
