# Generated by Django 5.1 on 2026-01-15 10:24

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_bio_alter_user_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 300x300 пикселей', max_length=500, null=True, upload_to=apps.users.models.user_avatar_upload_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткая информация о себе', max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Официальная должность в организации', max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('med', 'Медслужба'), ('saok', 'САОК'), ('admin', 'Админ')], default='hr', max_length=20, verbose_name='Роль'),
        ),
    ]
