# Generated by Django 5.1 on 2026-02-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('med', 'Медслужба'), ('admin', 'Админ'), ('hr_tev', 'HR-ТЕВ'), ('hr_corp', 'HR-Корп.Развитие'), ('hr_ac', 'HR- AC')], max_length=20, verbose_name='Роль'),
        ),
    ]
