# Generated by Django 5.1 on 2025-12-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Hr', 'HR'), ('Медслужба', 'Медслужба'), ('САОК', 'САОК'), ('Админ', 'Админ')], default='hr', max_length=20, verbose_name='Роль'),
        ),
    ]
