# Generated by Django 5.1 on 2025-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Медслужба', 'Медслужба'), ('САОК', 'САОК'), ('Админ', 'Админ')], default='HR', max_length=20, verbose_name='Роль'),
        ),
    ]
