# Generated by Django 5.1 on 2025-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('med', 'Медслужба'), ('saok', 'САОК'), ('admin', 'Админ')], default='hr', max_length=20, verbose_name='Роль'),
        ),
    ]
