# Generated by Django 5.1 on 2026-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('med', 'Медслужба'), ('admin', 'Админ'), ('hr_tev', 'HR-ТЕВ'), ('hr_corp', 'HR-Корп.развитие'), ('hr_ac', 'HR-AC')], max_length=20, verbose_name='Роль'),
        ),
    ]
