# Generated by Django 5.1 on 2026-01-19 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_levelhistory_new_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('student', 'Кот (студент)'), ('college', 'Колледжист (не кот)')], help_text='Кот или обычный колледжист', max_length=20, verbose_name='Тип человека')),
                ('full_name', models.CharField(blank=True, help_text='ФИО для колледжиста или авто для кота', max_length=200, verbose_name='ФИО')),
                ('reason', models.TextField(help_text='Почему вызван к HR', verbose_name='Причина вызова')),
                ('solution', models.TextField(blank=True, help_text='Что решили на приёме', verbose_name='Решение')),
                ('visit_datetime', models.DateTimeField(blank=True, help_text='Вручную указывается когда посетил', null=True, verbose_name='Дата и время посещения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hr_calls', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_calls', to='students.student', verbose_name='Кот (если студент)')),
            ],
            options={
                'verbose_name': 'Вызов к HR',
                'verbose_name_plural': 'Вызовы к HR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HrComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('hr_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr_calls.hrcall', verbose_name='Вызов')),
            ],
            options={
                'verbose_name': 'Комментарий к вызову',
                'verbose_name_plural': 'Комментарии к вызовам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HrFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hr_calls/files/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('hr_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hr_calls.hrcall', verbose_name='Вызов')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл к вызову',
                'verbose_name_plural': 'Файлы к вызовам',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
