# Generated by Django 5.1 on 2026-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrcall',
            name='problem_resolved',
            field=models.BooleanField(default=False, help_text='Если True — статус кота автоматически возвращается на active', verbose_name='Проблема решена'),
        ),
        migrations.AlterField(
            model_name='hrcall',
            name='full_name',
            field=models.CharField(blank=True, help_text='ФИО для колледжиста (обязательно) или авто для кота', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='hrcall',
            name='reason',
            field=models.TextField(blank=True, help_text='Почему вызван к HR', verbose_name='Причина вызова'),
        ),
    ]
