# Generated by Django 5.1 on 2026-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_calls', '0002_hrcall_problem_resolved_alter_hrcall_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcall',
            name='person_type',
            field=models.CharField(choices=[('student', 'Кот (студент)'), ('college', 'Колледжист (не кот)')], default='college', help_text='Кот или обычный колледжист', max_length=20, verbose_name='Тип человека'),
        ),
    ]
