# Generated by Django 5.1 on 2026-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_calls', '0004_alter_hrcall_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrfile',
            name='file',
            field=models.FileField(max_length=1000, upload_to='hr_calls/files/', verbose_name='Файл'),
        ),
    ]
