# Generated by Django 5.1 on 2026-03-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_calls', '0002_hrcall_person_type_category'),
        ('hr_calls', '0005_alter_hrfile_file'),
    ]

    operations = [
    ]
