# Generated by Django 5.1 on 2026-03-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_calls', '0006_merge_20260319_1048'),
        ('students', '0020_fired_date_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcall',
            name='category',
            field=models.CharField(blank=True, choices=[('college', 'Колледжисты'), ('alabuga_start_sng', 'АС(СНГ)'), ('alabuga_start_rf', 'АС(РФ)'), ('alabuga_mulatki', 'АС(МИР)'), ('patriot', 'Патриоты')], help_text='Категория кота (выбирается автоматически по коту)', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='hrcall',
            name='person_type',
            field=models.CharField(choices=[('cat', 'Кот'), ('not_cat', 'Не кот')], help_text='Кот или обычный колледжист', max_length=20, verbose_name='Тип человека'),
        ),
        migrations.AlterField(
            model_name='hrcall',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_calls', to='students.student', verbose_name='Кот (если есть в базе)'),
        ),
    ]
