# Generated by Django 5.1 on 2026-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Всего котов')),
                ('active_students', models.PositiveIntegerField(default=0, verbose_name='Активные')),
                ('fired_students', models.PositiveIntegerField(default=0, verbose_name='Уволенные')),
                ('called_hr_students', models.PositiveIntegerField(default=0, verbose_name='Вызванные к HR (коты)')),
                ('level_changes_total', models.PositiveBigIntegerField(default=0, verbose_name='Всего изменений уровня')),
                ('new_students_total', models.PositiveIntegerField(default=0, verbose_name='Всего новых котов (за всё время)')),
                ('distribution_by_level', models.JSONField(default=dict, verbose_name='Распределение по уровням')),
                ('distribution_by_status', models.JSONField(default=dict, verbose_name='Распределение по статусам')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Снимок аналитики',
                'verbose_name_plural': 'Снимки аналитики',
            },
        ),
    ]
