# Generated by Django 5.1 on 2026-01-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticssnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='level_changes_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Изменения уровня (текущий месяц)'),
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='new_students_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Новые коты (текущий месяц)'),
        ),
    ]
