# Generated by Django 5.1 on 2026-01-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticssnapshot_level_changes_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='distribution_by_category',
            field=models.JSONField(default=dict, verbose_name='Распределение по категориям'),
        ),
    ]
