# Generated by Django 5.1 on 2026-03-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticssnapshot_distribution_by_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsDummy',
        ),
    ]
