# Generated by Django 5.1 on 2026-03-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_delete_analyticsdummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'permissions': [('can_view_analytics', 'Can view analytics dashboard')],
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsSnapshot',
        ),
    ]
