# Generated by Django 5.1.7 on 2025-12-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_last_changed_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID доски')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Канбан-доска',
            },
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.CharField(choices=[('black', 'Чёрный пояс'), ('red', 'Красный пояс'), ('yellow', 'Жёлтый пояс'), ('green', 'Зелёный пояс'), ('hr_call', 'Вызов к HR'), ('fired', 'Уволен')], max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название колонки')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Цвет (HEX)')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.kanbanboard')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StudentKanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.kanbancolumn')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='students.student')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='kanbancolumn',
            index=models.Index(fields=['board', 'id'], name='kanban_kanb_board_i_4c7da2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbancolumn',
            unique_together={('board', 'position')},
        ),
        migrations.AddIndex(
            model_name='studentkanbancard',
            index=models.Index(fields=['column'], name='kanban_stud_column__d5c1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='studentkanbancard',
            index=models.Index(fields=['student'], name='kanban_stud_student_cbafb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentkanbancard',
            constraint=models.UniqueConstraint(fields=('student', 'column'), name='unique_student_in_column'),
        ),
    ]
