# Generated by Django 5.1 on 2026-01-14 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID доски')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Канбан-доска',
                'verbose_name_plural': 'Канбан-доски',
            },
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('black', 'Чёрный уровень'), ('red', 'Красный уровень'), ('yellow', 'Жёлтый уровень'), ('green', 'Зелёный уровень')], max_length=30, verbose_name='Уровень')),
                ('title', models.CharField(max_length=100, verbose_name='Название колонки')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Цвет (HEX)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.kanbanboard')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StudentKanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция в колонке')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.kanbancolumn')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='students.student')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='kanbancolumn',
            index=models.Index(fields=['board', 'level'], name='kanban_kanb_board_i_fb374f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbancolumn',
            unique_together={('board', 'level')},
        ),
        migrations.AddIndex(
            model_name='studentkanbancard',
            index=models.Index(fields=['column'], name='kanban_stud_column__d5c1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='studentkanbancard',
            index=models.Index(fields=['student'], name='kanban_stud_student_cbafb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentkanbancard',
            constraint=models.UniqueConstraint(fields=('student',), name='one_card_per_student'),
        ),
    ]
