# Generated by Django 5.1 on 2026-01-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumn',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет (HEX)'),
        ),
    ]
