# Generated by Django 5.1 on 2025-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
        ('students', '0002_student_last_changed_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbanboard',
            options={'verbose_name': 'Канбан-доска', 'verbose_name_plural': 'Канбан-доски'},
        ),
        migrations.AlterModelOptions(
            name='studentkanbancard',
            options={'ordering': ['position'], 'verbose_name': 'Карточка студента', 'verbose_name_plural': 'Карточки студентов'},
        ),
        migrations.RemoveConstraint(
            model_name='studentkanbancard',
            name='unique_student_in_column',
        ),
        migrations.AddConstraint(
            model_name='studentkanbancard',
            constraint=models.UniqueConstraint(fields=('student',), name='one_card_per_student'),
        ),
    ]
