# Generated by Django 5.1 on 2025-12-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_kanbanboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumn',
            name='id',
            field=models.CharField(choices=[('black', 'Чёрный уровень'), ('red', 'Красный уровень'), ('yellow', 'Жёлтый уровень'), ('green', 'Зелёный уровень'), ('hr_call', 'Вызов к HR'), ('fired', 'Уволен')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
