# Generated by Django 5.1 on 2026-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_kanbancolumn_color_alter_kanbancolumn_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumn',
            name='level',
            field=models.CharField(choices=[('black', 'Чёрный уровень'), ('red', 'Красный уровень'), ('yellow', 'Жёлтый уровень'), ('green', 'Зелёный уровень'), ('fired', 'Уволенные')], max_length=30, verbose_name='Уровень'),
        ),
    ]
