# Generated by Django 5.1 on 2025-12-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_kanbancolumn_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentkanbancard',
            options={'ordering': ['position'], 'verbose_name': 'Карточка кота', 'verbose_name_plural': 'Карточки котов'},
        ),
    ]
