# Generated by Django 5.1 on 2026-01-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_kanbancolumn_level'),
        ('students', '0005_alter_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentkanbancard',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentkanbancard',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.kanbancolumn'),
        ),
        migrations.AlterField(
            model_name='studentkanbancard',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentkanbancard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='students.student'),
        ),
    ]
