# Generated by Django 5.1 on 2026-01-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_studentkanbancard_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentkanbancard',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.kanbancolumn'),
        ),
    ]
