# Generated by Django 5.1 on 2026-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_alter_studentkanbancard_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumn',
            name='color',
            field=models.CharField(choices=[('#000000', 'Чёрный'), ('#ef4444', 'Красный'), ('#eab308', 'Жёлтый'), ('#22c55e', 'Зелёный'), ('#6B7280', 'Серый'), ('#662374', 'Фиолетовый')], max_length=7, verbose_name='Цвет (HEX)'),
        ),
        migrations.AlterField(
            model_name='kanbancolumn',
            name='level',
            field=models.CharField(choices=[('black', 'Чёрный уровень'), ('red', 'Красный уровень'), ('yellow', 'Жёлтый уровень'), ('green', 'Зелёный уровень'), ('fired', 'Уволен'), ('', 'Без уровня')], max_length=30, verbose_name='Уровень'),
        ),
    ]
